### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by RE-A** [RE-A/Anime_Hair_Color_Detection#1]
## 1차 목표
- [ ] 얼굴 사진에서 눈동자 색깔 인식하기
  - [x] 2D 사진에서 얼굴만 잘라내기
  - [ ] 잘라낸 얼굴 사진을 데이터셋으로 가공하기
  - [ ] 잘라낸 얼굴 사진을 가공한 데이터셋에 라벨 붙여서 csv 등의 형태로 만들기
  - [ ] 이미지셋을 학습할 수 있는 텐서플로우 모델 만들기
  - [ ]  10개 정도 시험 학습 시키기

## 2차 목표
- [ ] 랜덤 2D 사진에서 눈동자 색깔 인식하기
   - [ ] 직접 2D 사진에서 얼굴만 인식할 수 있는 모델 만들기
